name: My Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: python appsecrets.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
